<?php

use App\Models\Country;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {

        Country::create(['id' => 'ABW,', 'name' => "Aruba"]);
        Country::create(['id' => 'AFG,', 'name' => "Afghanistan"]);
        Country::create(['id' => 'AGO,', 'name' => "Angola"]);
        Country::create(['id' => 'AIA,', 'name' => "Anguilla"]);
        Country::create(['id' => 'ALA,', 'name' => "Åland Islands"]);
        Country::create(['id' => 'ALB,', 'name' => "Albania"]);
        Country::create(['id' => 'AND,', 'name' => "Andorra"]);
        Country::create(['id' => 'ANT,', 'name' => "Netherlands Antilles"]);
        Country::create(['id' => 'ARE,', 'name' => "United Arab Emirates"]);
        Country::create(['id' => 'ARG,', 'name' => "Argentina"]);
        Country::create(['id' => 'ARM,', 'name' => "Armenia"]);
        Country::create(['id' => 'ASM,', 'name' => "American Samoa"]);
        Country::create(['id' => 'ATA,', 'name' => "Antarctica"]);
        Country::create(['id' => 'ATF,', 'name' => "French Southern and Antarctic Lands"]);
        Country::create(['id' => 'ATG,', 'name' => "Antigua and Barbuda"]);
        Country::create(['id' => 'AUS,', 'name' => "Australia"]);
        Country::create(['id' => 'AUT,', 'name' => "Austria"]);
        Country::create(['id' => 'AZE,', 'name' => "Azerbaijan"]);
        Country::create(['id' => 'BDI,', 'name' => "Burundi"]);
        Country::create(['id' => 'BEL,', 'name' => "Belgium"]);
        Country::create(['id' => 'BEN,', 'name' => "Benin"]);
        Country::create(['id' => 'BFA,', 'name' => "Burkina Faso"]);
        Country::create(['id' => 'BGD,', 'name' => "Bangladesh"]);
        Country::create(['id' => 'BGR,', 'name' => "Bulgaria"]);
        Country::create(['id' => 'BHR,', 'name' => "Bahrain"]);
        Country::create(['id' => 'BHS,', 'name' => "Bahamas"]);
        Country::create(['id' => 'BIH,', 'name' => "Bosnia and Herzegovina"]);
        Country::create(['id' => 'BLM,', 'name' => "Saint Barthelemy"]);
        Country::create(['id' => 'BLR,', 'name' => "Belarus"]);
        Country::create(['id' => 'BLZ,', 'name' => "Belize"]);
        Country::create(['id' => 'BMU,', 'name' => "Bermuda"]);
        Country::create(['id' => 'BOL,', 'name' => "Bolivia"]);
        Country::create(['id' => 'BRA,', 'name' => "Brazil"]);
        Country::create(['id' => 'BRB,', 'name' => "Barbados"]);
        Country::create(['id' => 'BRN,', 'name' => "Brunei Darussalam"]);
        Country::create(['id' => 'BTN,', 'name' => "Bhutan"]);
        Country::create(['id' => 'BVT,', 'name' => "Bouvet Island"]);
        Country::create(['id' => 'BWA,', 'name' => "Botswana"]);
        Country::create(['id' => 'CAF,', 'name' => "Central African Republic"]);
        Country::create(['id' => 'CAN,', 'name' => "Canada"]);
        Country::create(['id' => 'CCK,', 'name' => "Cocos (Keeling) Islands"]);
        Country::create(['id' => 'CHE,', 'name' => "Switzerland"]);
        Country::create(['id' => 'CHL,', 'name' => "Chile"]);
        Country::create(['id' => 'CHN,', 'name' => "China"]);
        Country::create(['id' => 'CIV,', 'name' => "Cote d'Ivoire"]);
        Country::create(['id' => 'CMR,', 'name' => "Cameroon"]);
        Country::create(['id' => 'COD,', 'name' => "Democratic Republic of the Congo"]);
        Country::create(['id' => 'COG,', 'name' => "Congo"]);
        Country::create(['id' => 'COK,', 'name' => "Cook Islands"]);
        Country::create(['id' => 'COL,', 'name' => "Colombia"]);
        Country::create(['id' => 'COM,', 'name' => "Comoros"]);
        Country::create(['id' => 'CPV,', 'name' => "Cape Verde"]);
        Country::create(['id' => 'CRI,', 'name' => "Costa Rica"]);
        Country::create(['id' => 'CUB,', 'name' => "Cuba"]);
        Country::create(['id' => 'CXR,', 'name' => "Christmas Island"]);
        Country::create(['id' => 'CYM,', 'name' => "Cayman Islands"]);
        Country::create(['id' => 'CYP,', 'name' => "Cyprus"]);
        Country::create(['id' => 'CZE,', 'name' => "Czech Republic"]);
        Country::create(['id' => 'DEU,', 'name' => "Germany"]);
        Country::create(['id' => 'DJI,', 'name' => "Djibouti"]);
        Country::create(['id' => 'DMA,', 'name' => "Dominica"]);
        Country::create(['id' => 'DNK,', 'name' => "Denmark"]);
        Country::create(['id' => 'DOM,', 'name' => "Dominican Republic"]);
        Country::create(['id' => 'DZA,', 'name' => "Algeria"]);
        Country::create(['id' => 'ECU,', 'name' => "Ecuador"]);
        Country::create(['id' => 'EGY,', 'name' => "Egypt"]);
        Country::create(['id' => 'ERI,', 'name' => "Eritrea"]);
        Country::create(['id' => 'ESH,', 'name' => "Western Sahara"]);
        Country::create(['id' => 'ESP,', 'name' => "Spain"]);
        Country::create(['id' => 'EST,', 'name' => "Estonia"]);
        Country::create(['id' => 'ETH,', 'name' => "Ethiopia"]);
        Country::create(['id' => 'FIN,', 'name' => "Finland"]);
        Country::create(['id' => 'FJI,', 'name' => "Fiji"]);
        Country::create(['id' => 'FLK,', 'name' => "Falkland Islands (Malvinas)"]);
        Country::create(['id' => 'FRA,', 'name' => "France"]);
        Country::create(['id' => 'FRO,', 'name' => "Faroe Islands"]);
        Country::create(['id' => 'FSM,', 'name' => "Micronesia, Federated States of"]);
        Country::create(['id' => 'GAB,', 'name' => "Gabon"]);
        Country::create(['id' => 'GBR,', 'name' => "United Kingdom"]);
        Country::create(['id' => 'GEO,', 'name' => "Georgia"]);
        Country::create(['id' => 'GGY,', 'name' => "Guernsey"]);
        Country::create(['id' => 'GHA,', 'name' => "Ghana"]);
        Country::create(['id' => 'GIB,', 'name' => "Gibraltar"]);
        Country::create(['id' => 'GIN,', 'name' => "Guinea"]);
        Country::create(['id' => 'GLP,', 'name' => "Guadeloupe"]);
        Country::create(['id' => 'GMB,', 'name' => "Gambia"]);
        Country::create(['id' => 'GNB,', 'name' => "Guinea-Bissau"]);
        Country::create(['id' => 'GNQ,', 'name' => "Equatorial Guinea"]);
        Country::create(['id' => 'GRC,', 'name' => "Greece"]);
        Country::create(['id' => 'GRD,', 'name' => "Grenada"]);
        Country::create(['id' => 'GRL,', 'name' => "Greenland"]);
        Country::create(['id' => 'GTM,', 'name' => "Guatemala"]);
        Country::create(['id' => 'GUF,', 'name' => "French Guiana"]);
        Country::create(['id' => 'GUM,', 'name' => "Guam"]);
        Country::create(['id' => 'GUY,', 'name' => "Guyana"]);
        Country::create(['id' => 'HKG,', 'name' => "Hong Kong"]);
        Country::create(['id' => 'HMD,', 'name' => "Heard Island and McDonald Islands"]);
        Country::create(['id' => 'HND,', 'name' => "Honduras"]);
        Country::create(['id' => 'HRV,', 'name' => "Croatia"]);
        Country::create(['id' => 'HTI,', 'name' => "Haiti"]);
        Country::create(['id' => 'HUN,', 'name' => "Hungary"]);
        Country::create(['id' => 'IDN,', 'name' => "Indonesia"]);
        Country::create(['id' => 'IMN,', 'name' => "Isle of Man"]);
        Country::create(['id' => 'IND,', 'name' => "India"]);
        Country::create(['id' => 'IOT,', 'name' => "British Indian Ocean Territory"]);
        Country::create(['id' => 'IRL,', 'name' => "Ireland"]);
        Country::create(['id' => 'IRN,', 'name' => "Iran (Islamic Republic of)"]);
        Country::create(['id' => 'IRQ,', 'name' => "Iraq"]);
        Country::create(['id' => 'ISL,', 'name' => "Iceland"]);
        Country::create(['id' => 'ISR,', 'name' => "Israel"]);
        Country::create(['id' => 'ITA,', 'name' => "Italy"]);
        Country::create(['id' => 'JAM,', 'name' => "Jamaica"]);
        Country::create(['id' => 'JEY,', 'name' => "Jersey"]);
        Country::create(['id' => 'JOR,', 'name' => "Jordan"]);
        Country::create(['id' => 'JPN,', 'name' => "Japan"]);
        Country::create(['id' => 'KAZ,', 'name' => "Kazakhstan"]);
        Country::create(['id' => 'KEN,', 'name' => "Kenya"]);
        Country::create(['id' => 'KGZ,', 'name' => "Kyrgyzstan"]);
        Country::create(['id' => 'KHM,', 'name' => "Cambodia"]);
        Country::create(['id' => 'KIR,', 'name' => "Kiribati"]);
        Country::create(['id' => 'KNA,', 'name' => "Saint Kitts and Nevis"]);
        Country::create(['id' => 'KOR,', 'name' => "Korea, Republic of"]);
        Country::create(['id' => 'KWT,', 'name' => "Kuwait"]);
        Country::create(['id' => 'LAO,', 'name' => "Lao People's Democratic Republic"]);
        Country::create(['id' => 'LBN,', 'name' => "Lebanon"]);
        Country::create(['id' => 'LBR,', 'name' => "Liberia"]);
        Country::create(['id' => 'LBY,', 'name' => "Libyan Arab Jamahiriya"]);
        Country::create(['id' => 'LCA,', 'name' => "Saint Lucia"]);
        Country::create(['id' => 'LIE,', 'name' => "Liechtenstein"]);
        Country::create(['id' => 'LKA,', 'name' => "Sri Lanka"]);
        Country::create(['id' => 'LSO,', 'name' => "Lesotho"]);
        Country::create(['id' => 'LTU,', 'name' => "Lithuania"]);
        Country::create(['id' => 'LUX,', 'name' => "Luxembourg"]);
        Country::create(['id' => 'LVA,', 'name' => "Latvia"]);
        Country::create(['id' => 'MAC,', 'name' => "Macau"]);
        Country::create(['id' => 'MAF,', 'name' => "Saint Martin"]);
        Country::create(['id' => 'MAR,', 'name' => "Morocco"]);
        Country::create(['id' => 'MCO,', 'name' => "Monaco"]);
        Country::create(['id' => 'MDA,', 'name' => "Republic of Moldova"]);
        Country::create(['id' => 'MDG,', 'name' => "Madagascar"]);
        Country::create(['id' => 'MDV,', 'name' => "Maldives"]);
        Country::create(['id' => 'MEX,', 'name' => "Mexico"]);
        Country::create(['id' => 'MHL,', 'name' => "Marshall Islands"]);
        Country::create(['id' => 'MKD,', 'name' => "The former Yugoslav Republic of Macedonia"]);
        Country::create(['id' => 'MLI,', 'name' => "Mali"]);
        Country::create(['id' => 'MLT,', 'name' => "Malta"]);
        Country::create(['id' => 'MMR,', 'name' => "Burma"]);
        Country::create(['id' => 'MNE,', 'name' => "Montenegro"]);
        Country::create(['id' => 'MNG,', 'name' => "Mongolia"]);
        Country::create(['id' => 'MNP,', 'name' => "Northern Mariana Islands"]);
        Country::create(['id' => 'MOZ,', 'name' => "Mozambique"]);
        Country::create(['id' => 'MRT,', 'name' => "Mauritania"]);
        Country::create(['id' => 'MSR,', 'name' => "Montserrat"]);
        Country::create(['id' => 'MTQ,', 'name' => "Martinique"]);
        Country::create(['id' => 'MUS,', 'name' => "Mauritius"]);
        Country::create(['id' => 'MWI,', 'name' => "Malawi"]);
        Country::create(['id' => 'MYS,', 'name' => "Malaysia"]);
        Country::create(['id' => 'MYT,', 'name' => "Mayotte"]);
        Country::create(['id' => 'NAM,', 'name' => "Namibia"]);
        Country::create(['id' => 'NCL,', 'name' => "New Caledonia"]);
        Country::create(['id' => 'NER,', 'name' => "Niger"]);
        Country::create(['id' => 'NFK,', 'name' => "Norfolk Island"]);
        Country::create(['id' => 'NGA,', 'name' => "Nigeria"]);
        Country::create(['id' => 'NIC,', 'name' => "Nicaragua"]);
        Country::create(['id' => 'NIU,', 'name' => "Niue"]);
        Country::create(['id' => 'NLD,', 'name' => "Netherlands"]);
        Country::create(['id' => 'NOR,', 'name' => "Norway"]);
        Country::create(['id' => 'NPL,', 'name' => "Nepal"]);
        Country::create(['id' => 'NRU,', 'name' => "Nauru"]);
        Country::create(['id' => 'NZL,', 'name' => "New Zealand"]);
        Country::create(['id' => 'OMN,', 'name' => "Oman"]);
        Country::create(['id' => 'PAK,', 'name' => "Pakistan"]);
        Country::create(['id' => 'PAN,', 'name' => "Panama"]);
        Country::create(['id' => 'PCN,', 'name' => "Pitcairn Islands"]);
        Country::create(['id' => 'PER,', 'name' => "Peru"]);
        Country::create(['id' => 'PHL,', 'name' => "Philippines"]);
        Country::create(['id' => 'PLW,', 'name' => "Palau"]);
        Country::create(['id' => 'PNG,', 'name' => "Papua New Guinea"]);
        Country::create(['id' => 'POL,', 'name' => "Poland"]);
        Country::create(['id' => 'PRI,', 'name' => "Puerto Rico"]);
        Country::create(['id' => 'PRK,', 'name' => "Korea, Democratic People's Republic of"]);
        Country::create(['id' => 'PRT,', 'name' => "Portugal"]);
        Country::create(['id' => 'PRY,', 'name' => "Paraguay"]);
        Country::create(['id' => 'PSE,', 'name' => "Palestine"]);
        Country::create(['id' => 'PYF,', 'name' => "French Polynesia"]);
        Country::create(['id' => 'QAT,', 'name' => "Qatar"]);
        Country::create(['id' => 'REU,', 'name' => "Reunion"]);
        Country::create(['id' => 'ROU,', 'name' => "Romania"]);
        Country::create(['id' => 'RUS,', 'name' => "Russia"]);
        Country::create(['id' => 'RWA,', 'name' => "Rwanda"]);
        Country::create(['id' => 'SAU,', 'name' => "Saudi Arabia"]);
        Country::create(['id' => 'SDN,', 'name' => "Sudan"]);
        Country::create(['id' => 'SEN,', 'name' => "Senegal"]);
        Country::create(['id' => 'SGP,', 'name' => "Singapore"]);
        Country::create(['id' => 'SGS,', 'name' => "South Georgia South Sandwich Islands"]);
        Country::create(['id' => 'SHN,', 'name' => "Saint Helena"]);
        Country::create(['id' => 'SJM,', 'name' => "Svalbard"]);
        Country::create(['id' => 'SLB,', 'name' => "Solomon Islands"]);
        Country::create(['id' => 'SLE,', 'name' => "Sierra Leone"]);
        Country::create(['id' => 'SLV,', 'name' => "El Salvador"]);
        Country::create(['id' => 'SMR,', 'name' => "San Marino"]);
        Country::create(['id' => 'SOM,', 'name' => "Somalia"]);
        Country::create(['id' => 'SPM,', 'name' => "Saint Pierre and Miquelon"]);
        Country::create(['id' => 'SRB,', 'name' => "Serbia"]);
        Country::create(['id' => 'STP,', 'name' => "Sao Tome and Principe"]);
        Country::create(['id' => 'SUR,', 'name' => "Suriname"]);
        Country::create(['id' => 'SVK,', 'name' => "Slovakia"]);
        Country::create(['id' => 'SVN,', 'name' => "Slovenia"]);
        Country::create(['id' => 'SWE,', 'name' => "Sweden"]);
        Country::create(['id' => 'SWZ,', 'name' => "Swaziland"]);
        Country::create(['id' => 'SYC,', 'name' => "Seychelles"]);
        Country::create(['id' => 'SYR,', 'name' => "Syrian Arab Republic"]);
        Country::create(['id' => 'TCA,', 'name' => "Turks and Caicos Islands"]);
        Country::create(['id' => 'TCD,', 'name' => "Chad"]);
        Country::create(['id' => 'TGO,', 'name' => "Togo"]);
        Country::create(['id' => 'THA,', 'name' => "Thailand"]);
        Country::create(['id' => 'TJK,', 'name' => "Tajikistan"]);
        Country::create(['id' => 'TKL,', 'name' => "Tokelau"]);
        Country::create(['id' => 'TKM,', 'name' => "Turkmenistan"]);
        Country::create(['id' => 'TLS,', 'name' => "Timor-Leste"]);
        Country::create(['id' => 'TON,', 'name' => "Tonga"]);
        Country::create(['id' => 'TTO,', 'name' => "Trinidad and Tobago"]);
        Country::create(['id' => 'TUN,', 'name' => "Tunisia"]);
        Country::create(['id' => 'TUR,', 'name' => "Turkey"]);
        Country::create(['id' => 'TUV,', 'name' => "Tuvalu"]);
        Country::create(['id' => 'TWN,', 'name' => "Taiwan"]);
        Country::create(['id' => 'TZA,', 'name' => "United Republic of Tanzania"]);
        Country::create(['id' => 'UGA,', 'name' => "Uganda"]);
        Country::create(['id' => 'UKR,', 'name' => "Ukraine"]);
        Country::create(['id' => 'UMI,', 'name' => "United States Minor Outlying Islands"]);
        Country::create(['id' => 'URY,', 'name' => "Uruguay"]);
        Country::create(['id' => 'USA,', 'name' => "United States"]);
        Country::create(['id' => 'UZB,', 'name' => "Uzbekistan"]);
        Country::create(['id' => 'VAT,', 'name' => "Holy See (Vatican City)"]);
        Country::create(['id' => 'VCT,', 'name' => "Saint Vincent and the Grenadines"]);
        Country::create(['id' => 'VEN,', 'name' => "Venezuela"]);
        Country::create(['id' => 'VGB,', 'name' => "British Virgin Islands"]);
        Country::create(['id' => 'VIR,', 'name' => "United States Virgin Islands"]);
        Country::create(['id' => 'VNM,', 'name' => "Viet Nam"]);
        Country::create(['id' => 'VUT,', 'name' => "Vanuatu"]);
        Country::create(['id' => 'WLF,', 'name' => "Wallis and Futuna Islands"]);
        Country::create(['id' => 'WSM,', 'name' => "Samoa"]);
        Country::create(['id' => 'YEM,', 'name' => "Yemen"]);
        Country::create(['id' => 'ZAF,', 'name' => "South Africa"]);
        Country::create(['id' => 'ZMB,', 'name' => "Zambia"]);
        Country::create(['id' => 'ZWE,', 'name' => "Zimbabwe"]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        DB::table('countries')->truncate();
    }
};
